import { GridBgLayout } from '@/components/layout/grid-bg-layout';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-screen h-screen overflow-hidden">
      <GridBgLayout inverted className="grid-bg-layout px-8 md:px-0">
        <div className="z-10 relative">{children}</div>
      </GridBgLayout>
    </div>
  );
}
export const AmbientColor = () => {
  return (
    <div className="pointer-events-none absolute left-0 top-0 z-40 h-screen w-screen">
      <div
        style={{
          transform: 'translateY(-350px) rotate(-45deg)',
          width: '560px',
          height: '1380px',
          background:
            'radial-gradient(68.54% 68.72% at 55.02% 31.46%, hsla(50, 100%, 85%, .2) 0, hsla(50, 100%, 55%, .1) 50%, hsla(50, 100%, 45%, 0) 80%)',
        }}
        className="absolute left-0 top-0"
      />

      <div
        style={{
          transform: 'rotate(-45deg) translate(5%, -50%)',
          transformOrigin: 'top left',
          width: '240px',
          height: '1380px',
          background:
            'radial-gradient(50% 50% at 50% 50%, hsla(50, 100%, 85%, .15) 0, hsla(50, 100%, 55%, .1) 80%, transparent 100%)',
        }}
        className="absolute left-0 top-0"
      />

      <div
        style={{
          position: 'absolute',
          borderRadius: '20px',
          transform: 'rotate(-45deg) translate(-180%, -70%)',
          transformOrigin: 'top left',
          top: 0,
          left: 0,
          width: '240px',
          height: '1380px',
          background:
            'radial-gradient(50% 50% at 50% 50%, hsla(50, 100%, 85%, .1) 0, hsla(50, 100%, 45%, .05) 80%, transparent 100%)',
        }}
        className="absolute left-0 top-0"
      />
    </div>
  );
};
